### PR TITLE
original ReadAndSaveCfm.m

### PR DESCRIPTION
**Pull request by andreasplesch**
Brendan made me as the CFM developer aware  of this repo. Here is his original matlab script since, unfortunately, the linked CFM web pages evaporated.

### CODE REVIEW

**Comment by brendanjmeade** [comment]
I support this!

**Comment by brendanjmeade** [comment]
Awesome!

**Comment by kaeufl** [comment]
Hi Andreas and Brendan,
thanks a lot for thinking of that long forgotten repo :-) In fact, since you're the original authors and also since I'm not really doing anything with this any more, wouldn't it be better to move the scripts into one of your repos? Feel free to copy any bits you like. I'd then add a note to the readme and point to your repo.

**Comment by andreasplesch** [comment]
Hi Paul,

I had a largely unused CFM repo for this purpose and moved the scripts over:

https://github.com/andreasplesch/CFM/tree/master/ReadAndSaveCfm

Take a look and let me know if this is ok.

BTW, the CFM evolved quite a bit since 2014 (but is even harder to find now). We are always interested in following how the model is used.

**Pull request merged**
